version: "3.8"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - "mongo"
    container_name: graph-app
    volumes:
      - temp:/data/temp
      - libs:/data/libs
  mongo:
    image: "mongo:4.4.2"
    expose:
      - 27017
    container_name: mongo
    volumes:
      - db:/data/db
      - configdb:/data/configdb
      - ./mongodb-init:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_DATABASE: graph-app
      #MONGO_INITDB_ROOT_USERNAME: root
      #MONGO_INITDB_ROOT_PASSWORD: toor
volumes:
  db:
  configdb:
  temp:
  libs:
